// export const products = [
//     {
//         iphone: {
//             id:1,
//             title:"iphone",
//             items: [
//                 {
//                     title:"iPhone 7 Plus",
//                     price:600,
//                     description:"",
//                     memory: 32,
//                     stock: 3,
//                     category:"iphone-7",
//                     image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
//                     newProduct:false,
//                     sn:"i12",
//                     manufactured:"2016-09-01T00:00:00Z"

//                 },
//                 {
//                     title:"iPhone 7 Plus",
//                     price:650,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:1,
//                     image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
//                     newProduct:false,
//                     sn:"i13",
//                     manufactured:"2016-09-01T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 8",
//                     price:600,
//                     description:"",
//                     memory: 64,
//                     stock: 3,
//                     category:"iphone-8",
//                     image:"https://i.ibb.co/5Gky7XQ/iphone-8.jpg",
//                     newProduct:false,
//                     sn:"i14",
//                     manufactured:"2017-09-22T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 8 Plus",
//                     price:800,
//                     description:"",
//                     memory: 64,
//                     stock: 3,
//                     category:"iphone-8",
//                     image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
//                     newProduct:false,
//                     sn:"i15",
//                     manufactured:"2017-09-22T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 8 Plus",
//                     price:900,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:"iphone-8",
//                     image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
//                     newProduct:false,
//                     sn:"i16",
//                     manufactured:"2017-09-22T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone X",
//                     price:850,
//                     description:"",
//                     memory: 64,
//                     stock: 3,
//                     category:"iphone-x",
//                     image:"https://i.ibb.co/MNWmxd2/iphone-x.jpg",
//                     newProduct:false,
//                     sn:"i17",
//                     manufactured:"2017-11-03T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone XR",
//                     price:900,
//                     description:"",
//                     memory: 64,
//                     stock: 3,
//                     category:"iphone-x",
//                     image:"https://i.ibb.co/n8j52rM/iphone-xr.jpg",
//                     newProduct:false,
//                     sn:"i18",
//                     manufactured:"2018-10-26T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone XS MAX",
//                     price:1150,
//                     description:"",
//                     memory: 64,
//                     stock: 3,
//                     category:"iphone-x",
//                     image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
//                     newProduct:false,
//                     sn:"i19",
//                     manufactured:"2018-09-21T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone XS MAX",
//                     price:1250,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:"iphone-x",
//                     image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
//                     newProduct:false,
//                     sn:"i20",
//                     manufactured:"2018-09-21T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 11",
//                     price:1200,
//                     description:"",
//                     memory: 128,
//                     stock: 3,
//                     category:"iphone-11",
//                     image:"https://i.ibb.co/RCmz9bx/iphone-11.jpg",
//                     newProduct:false,
//                     sn:"i21",
//                     manufactured:"2019-09-20T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 11 Pro",
//                     price:1400,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:"iphone-11",
//                     image:"https://i.ibb.co/W2ddNbJ/iphone-11-Pro.jpg",
//                     newProduct:false,
//                     sn:"i223",
//                     manufactured:"2019-09-20T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 11 Pro Max",
//                     price:1750,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:"iphone-11",
//                     image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
//                     newProduct:false,
//                     sn:"i22",
//                     manufactured:"2019-09-20T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 11 Pro Max",
//                     price:1900,
//                     description:"",
//                     memory: 512,
//                     stock: 3,
//                     category:"iphone-11",
//                     image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
//                     newProduct:false,
//                     sn:"i23",
//                     manufactured:"2019-09-20T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 12",
//                     price:1550,
//                     description:"",
//                     memory: 128,
//                     stock: 3,
//                     category:"iphone-12",
//                     image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
//                     newProduct:true,
//                     sn:"i24",
//                     manufactured:"2020-10-23T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 12 Pro",
//                     price:1800,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:"iphone-12",
//                     image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
//                     newProduct:true,
//                     sn:"i25",
//                     manufactured:"2020-10-23T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 12 Pro",
//                     price:2000,
//                     description:"",
//                     memory: 512,
//                     stock: 3,
//                     category:"iphone-12",
//                     image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
//                     newProduct:true,
//                     sn:"i26",
//                     manufactured:"2020-10-23T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 12 Pro Max",
//                     price:2000,
//                     description:"",
//                     memory: 128,
//                     stock: 3,
//                     category:"iphone-12",
//                     image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
//                     newProduct:true,
//                     sn:"i27",
//                     manufactured:"2020-11-13T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 12 Pro Max",
//                     price:2200,
//                     description:"",
//                     memory: 256,
//                     stock: 3,
//                     category:"iphone-12",
//                     image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
//                     newProduct:true,
//                     sn:"i28",
//                     manufactured:"2020-11-13T00:00:00Z"
//                 },
//                 {
//                     title:"iPhone 12 Pro Max",
//                     price:2400,
//                     description:"",
//                     memory: 512,
//                     stock: 3,
//                     category:"iphone-12",
//                     image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
//                     newProduct:true,
//                     sn:"i29",
//                     manufactured:"2020-11-13T00:00:00Z"
//                 }
    
            
//             ]
//         }
//     }
    
// ]





export const devices = [
        {
                title:"iPhone 7",
                price:500,
                description:[
                    "Display 4.70-inch (750x1334)",
                    " Processor Apple A10 Fusion",
                    " Front Camera 7MP",
                    " Rear Camera 12MP",
                    " RAM 2GB",
                    " Storage 32GB",
                    " Battery Capacity 1960mAh",
                    " OS iOS 10"
                ],
                memory: "32 Gig",
                available: false,
                category:"iphone",
                image:"https://i.ibb.co/jRLJ4qY/iphone-7.jpg",
                newProduct:false,
                sn:"i001",
                related:"iphone-7",
                manufactured:"2016-09-16T00:00:00Z",
                colors:"Available upon order"
        },
                    {
                        title:"iPhone 7 Plus",
                        price:600,
                        description:[
                            " Retina HD display",
                            " 5.5-inch (diagonal) widescreen LCD",
                            " Multi-Touch display with IPS technology",
                            " 1920-by-1080-pixel resolution at 401 ppi",
                            " 1300:1 contrast ratio (typical)",
                            " Wide color display (P3)",
                            " 625 cd/m2 max brightness (typical)",
                            " Dual-domain pixels for wide viewing angles"
                        ],
                        memory: "32 Gig",
                        available: true,
                        category:"iphone",
                        image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
                        newProduct:false,
                        sn:"i002",
                        related:"iphone-7",
                        manufactured:"2016-09-16T00:00:00Z",
                        colors:"Available upon order"
                    },
                    {
                        title:"iPhone 7 Plus",
                        price:650,
                        description:[
                            " Retina HD display",
                            " 5.5-inch (diagonal) widescreen LCD",
                            " Multi-Touch display with IPS technology",
                            " 1920-by-1080-pixel resolution at 401 ppi",
                            " 1300:1 contrast ratio (typical)",
                            " Wide color display (P3)",
                            " 625 cd/m2 max brightness (typical)",
                            " Dual-domain pixels for wide viewing angles"
                        ],
                        memory: "256 Gig",
                        available: true,
                        category:"iphone",
                        image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
                        newProduct:false,
                        sn:"i003",
                        related:"iphone-7",
                        manufactured:"2016-09-16T00:00:00Z",
                        colors:"Available upon order"
                    },
                    {
                        title:"iPhone 8",
                        price:600,
                        description:[
                            "4.7 and 5.5-inch LCD display",
                            "Faster A11 processor",
                            "Glass body",
                            "Upgraded camera",
                            "Louder speakers",
                            "Wireless inductive charging"
                        ],
                        memory: "64 Gig",
                        available: true,
                        category:"iphone",
                        image:"https://i.ibb.co/5Gky7XQ/iphone-8.jpg",
                        newProduct:false,
                        sn:"i004",
                        related:"iphone-8",
                        manufactured:"2017-09-22T00:00:00Z",
                        colors:"Available upon order"
                    },
                    {
                    title:"iPhone 8 Plus",
                    price:800,
                    description:[
                        "Retina HD display",
                        "5.5-inch (diagonal) widescreen LCD Multi-Touch display with IPS technology",
                        "1920-by-1080-pixel resolution at 401 ppi",
                        "1300:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch",
                        "625 nits max brightness (typical)"
                    ],
                    memory: "64 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
                    newProduct:false,
                    sn:"i005",
                    related:"iphone-8",
                    manufactured:"2017-09-22T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 8 Plus",
                    price:900,
                    description:[
                        "Retina HD display",
                        "5.5-inch (diagonal) widescreen LCD Multi-Touch display with IPS technology",
                        "1920-by-1080-pixel resolution at 401 ppi",
                        "1300:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch",
                        "625 nits max brightness (typical)"
                    ],
                    memory: "256 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
                    newProduct:false,
                    sn:"i006",
                    related:"iphone-8",
                    manufactured:"2017-09-22T00:00:00Z",
                    colors:"Available upon order"
                },
        {
            title:"iPhone X",
            price:850,
            description:[
                "5.8 OLED display",
                "Faster A11 Bionic processor",
                "Glass body",
                "Edge-to-edge display",
                "Facial Recognition",
                "No Home button",
                "Wireless inductive charging",
                "Animoji"
            ],
            memory: "64 Gig",
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/MNWmxd2/iphone-x.jpg",
            newProduct:false,
            sn:"i007",
            related:"iphone-x",
            manufactured:"2017-11-03T00:00:00Z",
            colors:"Available upon order"
        },
        
                {
                    title:"iPhone XR",
                    price:900,
                    description:[
                        "6 New Colors",
                        "A12 Bionic Chip",
                        "Face ID and TrueDepth Camera System",
                        "Haptic Touch",
                        "Smart HDR",
                        "Portrait Mode on Single Camera",
                        "Dual SIM",
                        "Longer Battery Life"
                    ],
                    memory: "64 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/n8j52rM/iphone-xr.jpg",
                    newProduct:false,
                    sn:"i008",
                    related:"iphone-x",
                    manufactured:"2018-10-26T00:00:00Z",
                    colors:"Available upon order"
                },


                {
                    title:"iPhone XS MAX",
                    price:1150,
                    description:[
                        "Super Retina HD display",
                        "6.5‑inch (diagonal) all‑screen OLED Multi‑Touch display",
                        "HDR display",
                        "2688‑by-1242‑pixel resolution at 458 ppi",
                        "1,000,000:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch"
                    ],
                    memory: "64 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
                    newProduct:false,
                    sn:"i009",
                    related:"iphone-x",
                    manufactured:"2018-09-21T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone XS MAX",
                    price:1250,
                    description:[
                        "Super Retina HD display",
                        "6.5‑inch (diagonal) all‑screen OLED Multi‑Touch display",
                        "HDR display",
                        "2688‑by-1242‑pixel resolution at 458 ppi",
                        "1,000,000:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch"
                    ],
                    memory: "256 Gig",
                    available: true,
                    category:"iphone-x",
                    image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
                    newProduct:false,
                    sn:"i010",
                    related:"iphone-x",
                    manufactured:"2018-09-21T00:00:00Z",
                    colors:"Available upon order"
                },

        {
            title:"iPhone 11",
            price:950,
            description:[        
                "Processor: Apple A13 Bionic (7 nm+)",
                "RAM: 4 GB",
                "Storage: 64 GB, 128 GB, 256 GB",
                "Display: 6.1 inches",
                "Camera: 12 MP (wide) + 12 MP (ultrawide)",
                "Battery: Non-removable Li-Ion 3110 mAh battery + Fast battery charging 18W: 50% in 30 min",
            ],
            memory: "128 Gig",
            stock: 3,
            category:"iphone",
            image:"https://i.ibb.co/RCmz9bx/iphone-11.jpg",
            newProduct:false,
            sn:"i011",
            related:"iphone-11",
            manufactured:"2019-09-20T00:00:00Z",
            colors:"Available upon order"
        },
        {
            title:"iPhone 11",
            price:900,
            description:[        
                "Processor: Apple A13 Bionic (7 nm+)",
                "RAM: 4 GB",
                "Storage: 64 GB, 128 GB, 256 GB",
                "Display: 6.1 inches",
                "Camera: 12 MP (wide) + 12 MP (ultrawide)",
                "Battery: Non-removable Li-Ion 3110 mAh battery + Fast battery charging 18W: 50% in 30 min",
            ],
            memory: "64 Gig",
            stock: 3,
            category:"iphone",
            image:"https://i.ibb.co/RCmz9bx/iphone-11.jpg",
            newProduct:false,
            sn:"i021",
            related:"iphone-11",
            manufactured:"2019-09-20T00:00:00Z",
            colors:"Available upon order"
        },
                {
                    title:"iPhone 11 Pro",
                    price:1000,
                    description:[         
                        "Display. Screen size (inches) 5.80. Touchscreen",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: "64 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/W2ddNbJ/iphone-11-Pro.jpg",
                    newProduct:false,
                    sn:"i022",
                    related:"iphone-11",
                    manufactured:"2019-09-20T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 11 Pro",
                    price:1400,
                    description:[         
                        "Display. Screen size (inches) 5.80. Touchscreen",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: "256 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/W2ddNbJ/iphone-11-Pro.jpg",
                    newProduct:false,
                    sn:"i012",
                    related:"iphone-11",
                    manufactured:"2019-09-20T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1150,
                    description:[
                        "Display. Screen size (inches) 6.50. Touchscreen.",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: "64 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i023",
                    related:"iphone-11",
                    manufactured:"2019-09-20T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1750,
                    description:[
                        "Display. Screen size (inches) 6.50. Touchscreen.",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: "256 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i013",
                    related:"iphone-11",
                    manufactured:"2019-09-20T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1900,
                    description:[
                        "Display. Screen size (inches) 6.50. Touchscreen.",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: "512 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i014",
                    related:"iphone-11",
                    manufactured:"2019-09-20T00:00:00Z",
                    colors:"Available upon order"
                },    
                {
                    title:"iPhone 12",
                    price:1100,
                    description:[
                        "iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution",
                        " Dual camera setup on rear with features like autofocus and more",
                        " Front camera is of 12 MP",
                        " Runs iOS 14",
                        " 64GB inbuilt storage",
                        " Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams"
                    ],
                    memory: "64 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
                    newProduct:false,
                    sn:"i015",
                    related:"iphone-12",
                    manufactured:"2020-10-23T00:00:00Z",
                    colors:"Available upon order"
                },
                
        {
            title:"iPhone 12",
            price:1200,
            description:[
                "iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution",
                " Dual camera setup on rear with features like autofocus and more",
                " Front camera is of 12 MP",
                " Runs iOS 14",
                " 64GB inbuilt storage",
                " Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams"
            ],
            memory: "128 Gig",
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
            newProduct:false,
            sn:"i026",
            related:"iphone-12",
            manufactured:"2020-10-23T00:00:00Z",
            colors:"Available upon order"
        },
        {
            title:"iPhone 12",
            price:1250,
            description:[
                "iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution",
                " Dual camera setup on rear with features like autofocus and more",
                " Front camera is of 12 MP",
                " Runs iOS 14",
                " 64GB inbuilt storage",
                " Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams"
            ],
            memory: "256 Gig",
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
            newProduct:false,
            sn:"i024",
            related:"iphone-12",
            manufactured:"2020-10-23T00:00:00Z",
            colors:"Available upon order"
        },
        {
            title:"iPhone 12 Mini",
            price:1550,
            description:[
                "5.4″Super Retina XDR display",
                "Superfast downloads, high‑quality streaming",
                "Dolby Vision HDR video recording up to 30 fps",
                "2x Optical zoom range",
                "Fastest chip in a smartphone",
                "Up to 15 hours video playback",
                "Water resistant to a depth of 6 meters for up to 30 minutes"
            ],
            memory: "128 Gig",
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/JtPbQXB/compare-iphone12-mini-black-32g32p2j7hem-large.jpg",
            newProduct:false,
            sn:"i027",
            related:"iphone-12",
            manufactured:"2020-10-23T00:00:00Z",
            colors:"Available upon order"
        },
        {
            title:"iPhone 12 Pro",
            price:1350,
            description:["iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution.",
                "Dual camera setup on rear with features like autofocus and more.",
                "Front camera is of 12 MP.",
                "Runs iOS 14.",
                "64GB inbuilt storage.",
                "Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams."
            ],
            memory: "128 Gig",
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
            newProduct:false,
            sn:"i025",
            related:"iphone-12",
            manufactured:"2020-10-23T00:00:00Z",
            colors:"Available upon order"
        },
                {
                    title:"iPhone 12 Pro",
                    price:1450,
                    description:["iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution.",
                        "Dual camera setup on rear with features like autofocus and more.",
                        "Front camera is of 12 MP.",
                        "Runs iOS 14.",
                        "64GB inbuilt storage.",
                        "Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams."
                    ],
                    memory: "256 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
                    newProduct:false,
                    sn:"i016",
                    related:"iphone-12",
                    manufactured:"2020-10-23T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 12 Pro",
                    price:2000,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: "512 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
                    newProduct:false,
                    sn:"i017",
                    related:"iphone-12",
                    manufactured:"2020-10-23T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:1500,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: "128 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:false,
                    sn:"i018",
                    related:"iphone-12",
                    manufactured:"2020-11-13T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:1600,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: "256 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:false,
                    sn:"i019",
                    related:"iphone-12",
                    manufactured:"2020-11-13T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:1800,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: "512 Gig",
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:false,
                    sn:"i020",
                    related:"iphone-12",
                    manufactured:"2020-11-13T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch Series 3",
                    price:380,
                    description:["Built-in GPS and GLONASS",
                    "Barometric altimeter",
                    "Water resistant to 50 meters under ISO standard 22810:2010",
                    "Heart rate sensor",
                    "Accelerometer",
                    "Gyroscope",
                    "Ambient light sensor",
                    "Siri speaks"],
                    memory: "40mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/74YpmPL/watch-series-3.jpg",
                    newProduct:false,
                    sn:"iw004",
                    related:"watch-3",
                    manufactured:"2017-09-22T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch Series 4",
                    price:480,
                    description:["GPS, GLONASS, Galileo, and QZSS",
                    "Barometric altimeter",
                    "Water resistant. 50 meters",
                    "Electrical heart sensor",
                    "Optical heart sensor",
                    "Improved accelerometer. up to 32 g-forces",
                    "Improved gyroscope",
                    "Ambient light sensor"],
                    memory: "42mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/rxxqQvT/watch-series-4.jpg",
                    newProduct:false,
                    sn:"iw005",
                    related:"watch-4",
                    manufactured:"2018-09-21T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch Series 5",
                    price:550,
                    description:["GPS/GNSS",
                    "Compass",
                    "Barometric altimeter",
                    "Water resistant",
                    "50 meters",
                    "Electrical heart sensor",
                    "Second-generation optical heart sensor",
                    "International emergency calling",
                    "Emergency SOS",
                    "Accelerometer"],
                    memory: "44mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/jgcRQ26/all-models-s5-b1wqs7qtdkfm-large.png",
                    newProduct:false,
                    sn:"iw001",
                    related:"watch-5",
                    manufactured:"2019-09-26T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch SE",
                    price:500,
                    description:[
                        "Retina display",
                        "Water resistant",
                        "Cycle Tracking",
                        "Redesigned Compass app with waypoints and Backtrack",
                        "Up to 18 hours",
                        "Available cellular connectivity",
                   ],
                    memory: "40mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/jznYdwD/se.jpg",
                    newProduct:true,
                    sn:"iw006",
                    related:"watch-SE",
                    manufactured:"2022-09-18T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch SE",
                    price:560,
                    description:[
                        "Retina display",
                        "Water resistant",
                        "Cycle Tracking",
                        "Redesigned Compass app with waypoints and Backtrack",
                        "Up to 18 hours",
                        "Available cellular connectivity",
                   ],
                    memory: "44mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/jznYdwD/se.jpg",
                    newProduct:true,
                    sn:"iw009",
                    related:"watch-SE",
                    manufactured:"2022-09-18T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch Series 6",
                    price:650,
                    description:["Accelerometer", 
                    "gyro", 
                    "heart rate (2nd gen)",
                    "barometer", 
                     "always-on altimeter", 
                     "compass", 
                     "SpO2", 
                     "VO2max"],
                    memory: "42mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/JcGQXst/watch-series-6.png",
                    newProduct:false,
                    sn:"iw002",
                    related:"watch-6",
                    manufactured:"2020-09-18T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Apple Watch Series 6",
                    price:800,
                    description:["Accelerometer", 
                    "gyro", 
                    "heart rate (2nd gen)",
                    "barometer", 
                    "always-on altimeter", 
                    "compass", 
                    "SpO2", 
                    "VO2max"],
                    memory: "44mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/JcGQXst/watch-series-6.png",
                    newProduct:false,
                    sn:"iw003",
                    related:"watch-6",
                    manufactured:"2020-09-18T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPad 7th Gen",
                    price:700,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: "128 Gig",
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/g3Pnx9v/ipad-7thgen.jpg",
                    newProduct:false,
                    sn:"ip001",
                    related:"ipad",
                    manufactured:"2019-09-25T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPad 8th Gen",
                    price:800,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: "128 Gig",
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/g3Pnx9v/ipad-7thgen.jpg",
                    newProduct:false,
                    sn:"ip002",
                    related:"ipad",
                    manufactured:"2020-09-18T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPad Air 2020",
                    price:1300,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: "128 Gig",
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/029qhVN/ipad-air-1st-gen-silver.jpg",
                    newProduct:false,
                    sn:"ip003",
                    related:"ipad-air",
                    manufactured:"2020-10-23T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPad Pro 2020",
                    price:1700,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: "128 Gig",
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/9bxfxmt/ipad-pro-11.jpg",
                    newProduct:false,
                    sn:"ip004",
                    related:"ipad-pro",
                    manufactured:"2020-03-25T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"iPad Pro 2020",
                    price:2100,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: "128 Gig",
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/9bxfxmt/ipad-pro-11.jpg",
                    newProduct:false,
                    sn:"ip005",
                    related:"ipad-pro",
                    manufactured:"2020-03-25T00:00:00Z",
                    colors:"Available upon order"
                },

                {
                    title:"Airpod 1st Gen",
                    price:200,
                    description:[
                        "Zero wires",
                        "Comfortable fit",
                        "Five hour battery life",
                        "24 hour total battery life with Charging Case",
                        "3 hours charge from case in 15 minutes",
                        "One tap setup for Apple devices",
                        "Instant connection to ‌iPhone‌, ‌iPad‌, Mac, or Apple Watch",
                        "Easy switching between iOS and Mac devices"
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/wK3fffV/MRXJ2.png",
                    newProduct:false,
                    sn:"ia001",
                    related:"airpod-pro",
                    manufactured:"2016-12-13T00:00:00Z",
                    colors:""
                },
                {
                    title:"Airpod 2nd Gen",
                    price:200,
                    description:[
                        "Zero wires",
                        "Comfortable fit",
                        "Five hour battery life",
                        "24 hour total battery life with Charging Case",
                        "3 hours charge from case in 15 minutes",
                        "One tap setup for Apple devices",
                        "Instant connection to ‌iPhone‌, ‌iPad‌, Mac, or Apple Watch",
                        "Easy switching between iOS and Mac devices"
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/wK3fffV/MRXJ2.png",
                    newProduct:false,
                    sn:"ia002",
                    related:"airpod-pro",
                    manufactured:"2019-03-20T00:00:00Z",
                    colors:""
                },
                {
                    title:"Airpod Pro",
                    price:380,
                    description:["Active Noise Cancellation",
                    "Adaptive EQ",
                    "Dual beamforming microphones",
                    "Force sensor",
                    "Sweat and water resistant (IPX4)",
                    "Vent system for pressure equalization",
                    "Spatial audio with dynamic head tracking",
                    "Dual optical sensors",
                    "Speech-detecting accelerometer"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/XFw90tX/airpods-pro-qwgxmyvspfey-large.jpg",
                    newProduct:false,
                    sn:"ia003",
                    related:"airpod-pro",
                    manufactured:"2019-10-30T00:00:00Z",
                    colors:""
                },
                {
                    title:"EarPods Lightning",
                    price:45,
                    description:["The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. "],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/jL9F0xB/MMTN2.jpg",
                    newProduct:false,
                    sn:"ias002",
                    related:"earpods",
                    manufactured:"2016-09-16T00:00:00Z",
                    colors:""
                },
                {
                    title:"EarPods Jack",
                    price:30,
                    description:["The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. "],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/BN4rL6b/MD827.jpg",
                    newProduct:false,
                    sn:"ias003",
                    related:"earpods",
                    manufactured:"2012-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"Lightning",
                    price:30,
                    description:["This USB 2.0 cable connects your iPhone, iPad, or iPod with Lightning connector to your computer’s USB port for syncing and charging. Or you can connect to the Apple USB Power Adapter for convenient charging from a wall outlet."],
                    memory: "up to 2m",
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/v1t5gm4/MD818.jpg",
                    newProduct:false,
                    sn:"ias004",
                    related:"cable",
                    manufactured:"2012-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"9D(6-8 Plus)",
                    price:15,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/c1xSnTB/shutter-glass.jpg",
                    newProduct:false,
                    sn:"ias005",
                    related:"tempered",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"9D(X- 11 Pro Max)",
                    price:20,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/c1xSnTB/shutter-glass.jpg",
                    newProduct:false,
                    sn:"ias006",
                    related:"tempered",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"9D(iphone 12- 12 Pro Max)",
                    price:40,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/c1xSnTB/shutter-glass.jpg",
                    newProduct:false,
                    sn:"ias007",
                    related:"tempered",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"Privacy",
                    price:40,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/c1xSnTB/shutter-glass.jpg",
                    newProduct:false,
                    sn:"ias008",
                    related:"tempered",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"Silicon Case",
                    price:20,
                    description:["100% Brand New and high quality!",
                    "Extreme Protection", "iphone 6 - 8 Plus"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/n05hF6L/silicone-case.png",
                    newProduct:false,
                    sn:"ias009",
                    related:"silicon",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Silicon Case",
                    price:40,
                    description:["100% Brand New and high quality!",
                    "Extreme Protection", "iphone X - 12 Pro Max"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/n05hF6L/silicone-case.png",
                    newProduct:false,
                    sn:"ias010",
                    related:"silicon",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"Clear Case",
                    price:15,
                    description:["100% Brand New and high quality!",
                    "Beautiful Design", "iphone 6 - 8 Plus"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/f1g9dTw/clear-pouch.jpg",
                    newProduct:false,
                    sn:"ias011",
                    related:"clear",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:""
                },

                {
                    title:"Clear Case",
                    price:30,
                    description:["100% Brand New and high quality!",
                    "Beautiful Design", "iphone X - 12 Pro Max"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/f1g9dTw/clear-pouch.jpg",
                    newProduct:false,
                    sn:"ias012",
                    related:"clear",
                    manufactured:"2015-09-12T00:00:00Z",
                    colors:""
                },
                {
                    title:"MacBook Air M1",
                    price:2000,
                    description:["13.3” Retina display",
                    "8-coreApple M1 chip", "Up to16GB unified memory", "Up to 2TBstorage", "Up to 18 hrsbattery life", "Touch ID"],
                    memory: "512 Gig",
                    available: true,
                    category:"macbook",
                    image:"https://i.ibb.co/znYDjSL/compare-macbook-air-retina-gold-ewleoaqvx7qu-large.jpg",
                    newProduct:false,
                    sn:"mac001",
                    related:"mac-air",
                    manufactured:"2020-09-12T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"MacBook Air M1",
                    price:1800,
                    description:["13.3” Retina display",
                    "8-coreApple M1 chip", "Up to16GB unified memory", "Up to 2TBstorage", "Up to 18 hrsbattery life", "Touch ID"],
                    memory: "256 Gig",
                    available: true,
                    category:"macbook",
                    image:"https://i.ibb.co/znYDjSL/compare-macbook-air-retina-gold-ewleoaqvx7qu-large.jpg",
                    newProduct:false,
                    sn:"mac004",
                    related:"mac-air",
                    manufactured:"2020-09-12T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"MacBook Pro",
                    price:2200,
                    description:["13.3” Retina display",
                    "8-coreApple M1 chip", "Up to16GB unified memory", "Up to 2TBstorage", "Up to 20 hrsbattery life", "Touch Bar and Touch ID"],
                    memory: "256 Gig",
                    available: true,
                    category:"macbook",
                    image:"https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
                    newProduct:false,
                    sn:"mac002",
                    related:"mac-pro",
                    manufactured:"2020-09-12T00:00:00Z",
                    colors:"Available upon order"
                },
                {
                    title:"MacBook Pro",
                    price:2400,
                    description:["13.3” Retina display",
                    "8-coreApple M1 chip", "Up to16GB unified memory", "Up to 2TBstorage", "Up to 20 hrsbattery life", "Touch Bar and Touch ID"],
                    memory: "512 Gig",
                    available: true,
                    category:"macbook",
                    image:"https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
                    newProduct:false,
                    sn:"mac003",
                    related:"mac-pro",
                    manufactured:"2020-09-12T00:00:00Z",
                    colors:"Available upon order"
                },

                   
{
    available:true,
    category:"ipad",
    colors: "Available upon order",
    description :[
    "7.9 in. Retina display True Tone",
    "A12 Bionic chip with Neural Engine",
    "Up to 256GB",
    "8MP Wide camera",
    "7MP FaceTime HD camera",
    "Lightning connector",
    "4G LTE cellular",
    "Works with Bluetooth keyboards",
],
image: "https://i.ibb.co/0YSPF7b/ipad-mini-5th-gen-gold-ghmahqpjmb2a-large.jpg",
manufactured:"2021-10-23T00:00:00Z",
memory:"64 Gig",
newProduct:false,
price:650,
related:"ipad-mini",
sn:"ip009",
title:"iPad Mini 5" 
},


{
    available: true,
    category:"macbook",
    colors:"Available upon order",
    description: [
        "13.3” Retina display",
        "8-coreApple M1 chip",
        "Up to16GB unified memory",
        "Up to 2TBstorage",
        "Up to 18 hrsbattery life",
        "Touch ID",
    ],
    image:"https://i.ibb.co/znYDjSL/compare-macbook-air-retina-gold-ewleoaqvx7qu-large.jpg",
    manufactured: "2020-09-12T00:00:00Z",
    memory:"512 Gig",
    newProduct:false,
    price:2400,
    related:"mac-air",
    sn:"mac001",
    title:"MacBook Air M1",
},

{
    
available:true,
category:"macbook",
colors:"Available upon order",
description:[
    "13.3” Retina display",
    "8-coreApple M1 chip",
    "Up to16GB unified memory",
    "Up to 2TBstorage",
    "Up to 18 hrsbattery life",
    "Touch ID",
],
image: "https://i.ibb.co/znYDjSL/compare-macbook-air-retina-gold-ewleoaqvx7qu-large.jpg",
manufactured: "2020-09-12T00:00:00Z",
memory: "256 Gig",
newProduct: false,
price: 1500,
related: "mac-air",
sn: "mac004",
title: "MacBook Air M1 2020"

},

{
    
available:true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.7 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 28 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers"
],

image: "https://i.ibb.co/gZJvS7M/compare-iphone13-pro-max-sierra-blue-clciothwemj6-large.jpg",
manufactured: "2021-10-24T07:00:00Z",
memory: "512 Gig",
newProduct: false,
price: 2000,
related: "iphone-13-pro-max",
sn: "i037",
title: "iPhone 13 Pro Max" ,
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.7 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 28 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers"
],
image: "https://i.ibb.co/gZJvS7M/compare-iphone13-pro-max-sierra-blue-clciothwemj6-large.jpg",
manufactured: "2021-10-24T07:00:00Z",
memory: "128 Gig",
newProduct: false,
price: 1650,
related: "iphone-13-pro-max",
sn: "i035",
title: "iPhone 13 Pro Max",
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.7 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 28 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers",
],

image: "https://i.ibb.co/gZJvS7M/compare-iphone13-pro-max-sierra-blue-clciothwemj6-large.jpg",
manufactured: "2021-10-24T07:00:00Z",
memory: "256 Gig",
newProduct: false,
price: 1850,
related: "iphone-13-pro-max",
sn: "i036",
title: "iPhone 13 Pro Max"

},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description: [
    "6.7 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 28 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers",
],

image: "https://i.ibb.co/gZJvS7M/compare-iphone13-pro-max-sierra-blue-clciothwemj6-large.jpg",
manufactured: "2021-10-24T07:00:00Z",
memory: "1TB",
newProduct: false,
price: 2550,
related: "iphone-13-pro-max",
sn: "i038",
title: "iPhone 13 Pro Max",

},

{
    
available: true,
category: "ipad",
colors: "Available upon order",
description: [
    "8.3 in. Liquid Retina display True Tone",
    "A15 Bionic chip with Neural Engine",
    "12MP Wide camera",
    "12MP Ultra Wide front camera",
    "USB-C connector",
    "5G Superfast downloads, high-quality streaming",
    "Works with Apple Pencil (2nd generation)",
    "Works with Bluetooth keyboards",
],
image: "https://i.ibb.co/JnK1Dx8/ipad-mini-6th-gen-starlight-cro88sbvo866-large.jpg",
manufactured: "2021-10-23T00:00:00Z",
memory: "256 Gig",
newProduct: false,
price: 1250,
related: "ipad-mini",
sn: "ip007",
title: "iPad Mini",

},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.1 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 22 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers",
],

image: "https://i.ibb.co/mTFXhQw/compare-iphone13-pro-gold-ew89cgtje4wi-large.jpg",
manufactured: "2021-10-24T08:00:00Z",
memory: "1TB",
newProduct: false,
price: 2300,
related: "iphone-13-pro",
sn: "i034",
title: "iPhone 13 Pro",
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.1 inch Super Retina XDR display",
    "Superfast downloads, high‑quality streaming - 5G",
    "2x Optical zoom range",
    "Up to 19 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers",
],

image: "https://i.ibb.co/zm5rwhF/compare-iphone13-midnight-fjqo0zcgqaaa-large.jpg",
manufactured: "2021-10-24T09:00:00Z",
memory: "512 Gig",
newProduct: false,
price: 1600,
related: "iphone-13",
sn: "i030",
title: "iPhone 13" 
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.1 inch Super Retina XDR display",
    "Superfast downloads, high‑quality streaming - 5G",
    "2x Optical zoom range",
    "Up to 19 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers",
],
image: "https://i.ibb.co/zm5rwhF/compare-iphone13-midnight-fjqo0zcgqaaa-large.jpg",
manufactured: "2021-10-24T09:00:00Z",
memory: "128 Gig",
newProduct: false,
price: 1200,
related: "iphone-13",
sn: "i028",
title: "iPhone 13",
},
{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.1 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 22 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers"
],
image: "https://i.ibb.co/mTFXhQw/compare-iphone13-pro-gold-ew89cgtje4wi-large.jpg",
manufactured: "2021-10-24T08:00:00Z",
memory: "512 Gig",
newProduct: false,
price: 1850,
related: "iphone-13-pro",
sn: "i033",
title: "iPhone 13 Pro" 
},

{
    
available:true,
category:"macbook",
colors:"Available upon order",
description:[
    "13.3” Retina display",
    "8-coreApple M1 chip",
    "Up to16GB unified memory",
    "Up to 2TBstorage",
    "Up to 20 hrsbattery life",
    "Touch Bar and Touch ID"
],

image: "https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
manufactured: "2020-09-12T00:00:00Z",
memory: "256 Gig",
newProduct: false,
price: 1800,
related: "mac-pro",
sn: "mac002",
title: "MacBook Pro 2020" 
},

{
    
available: true,
category: "macbook",
colors: "Available upon order",
description:[
    "24 inch 4.5K Retina display",
    "1080p FaceTime HD camera",
    "Apple M1 chip",
    "Magic Keyboard with Touch ID",
    "Up to 16GB unified memory",
    "Up to 2TB storage"
],
image: "https://i.ibb.co/W61tCB2/compare-imac-24-silver-egicv98iatci-large.jpg",
manufactured: "2020-09-12T10:00:00Z",
memory: "256 SSD",
newProduct: false,
price: 2200,
related: "mac-pro",
sn: "mac007",
title: "iMac"
},

{
    
available: true,
category: "macbook",
colors: "Available upon order",
description:[
    "14.2 Liquid Retina XDR display",
    "Apple M1 Pro chip or Apple M1 Max chip",
    "Up to 10-coreCPU",
    "Up to 32-core GPU",
    "Up to 64GB unified memory",
    "Up to 17 hrs battery life",
    "Touch ID"
],
image: "https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
manufactured: "2021-09-12T10:00:00Z",
memory: "512 SSD",
newProduct: false,
price: 2450,
related: "mac-pro",
sn: "mac006",
title: "MacBook Pro 2021" 
},

{
    
available: true,
category: "macbook",
colors: "Available upon order",
description:[
    "16 inch Retina display",
    "Intel Core i9",
    "Up to16GB unified memory",
    "Up to 2TBstorage",
    "Up to 20 hrsbattery life",
    "Touch Bar and Touch ID"
],
image: "https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
manufactured: "2020-09-12T10:00:00Z",
memory: "1TB SSD",
newProduct: false,
price: 3250,
related: "mac-pro",
sn: "mac008",
title: "MacBook Pro 2020" 
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.1 inch Super Retina XDR display",
    "Superfast downloads, high‑quality streaming - 5G",
    "2x Optical zoom range",
    "Up to 19 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers"
],
image: "https://i.ibb.co/zm5rwhF/compare-iphone13-midnight-fjqo0zcgqaaa-large.jpg",
manufactured: "2021-10-24T09:00:00Z",
memory: "256 Gig",
newProduct: false,
price: 1350,
related: "iphone-13",
sn: "i029",
title: "iPhone 13",
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description:[
    "6.1 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 22 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers",
],
image: "https://i.ibb.co/mTFXhQw/compare-iphone13-pro-gold-ew89cgtje4wi-large.jpg",
manufactured: "2021-10-24T08:00:00Z",
memory: "128 Gig",
newProduct: false,
price: 1550,
related: "iphone-13-pro",
sn: "i031",
title: "iPhone 13 Pro" 
},

{
    
available: true,
category: "iphone",
colors: "Available upon order",
description: [
    "6.1 inch Super Retina XDR display with ProMotion",
    "Superfast downloads, high‑quality streaming - 5G",
    "6x Optical zoom range",
    "LiDAR Scanner for Night mode portraits, faster autofocus in low light, and next-level AR experiences",
    "Up to 22 hours video playback",
    "Water resistant to a depth of 6 meters for up to 30 minutes",
    "Compatible with MagSafe accessories and wireless chargers"
],
image: "https://i.ibb.co/mTFXhQw/compare-iphone13-pro-gold-ew89cgtje4wi-large.jpg",
manufactured: "2021-10-24T08:00:00Z",
memory: "256 Gig",
newProduct: false,
price: 1700,
related: "iphone-13-pro",
sn: "i032",
title: "iPhone 13 Pro"

},

{
    
available: true,
category: "ipad",
colors: "Available upon order",
description:[
    "8.3 in. Liquid Retina display True Tone",
    "A15 Bionic chip with Neural Engine",
    "12MP Wide camera",
    "12MP Ultra Wide front camera",
    "USB-C connector",
    "5G Superfast downloads, high-quality streaming",
    "Works with Apple Pencil (2nd generation)",
    "Works with Bluetooth keyboards"
],

image: "https://i.ibb.co/JnK1Dx8/ipad-mini-6th-gen-starlight-cro88sbvo866-large.jpg",
manufactured: "2021-10-23T00:00:00Z",
memory: "64 Gig",
newProduct: false,
price: 950,
related: "ipad-mini",
sn: "ip006",
title: "iPad Mini" 
},

{
    
available: true,
category: "macbook",
colors: "Available upon order",
description:[
    "14.2 Liquid Retina XDR display",
    "Apple M1 Pro chip or Apple M1 Max chip",
    "Up to 10-coreCPU",
    "Up to 32-core GPU",
    "Up to 64GB unified memory",
    "Up to 17 hrs battery life",
    "Touch ID"
],
image: "https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
manufactured: "2021-09-12T10:00:00Z",
memory: "256 SSD",
newProduct: false,
price: 2100,
related: "mac-pro",
sn: "mac005",
title: "MacBook Pro 2021" 
},

{
    
available: true,
category: "macbook",
colors: "Available upon order",
description:[
    "13.3” Retina display",
    "Intel Core i5",
    "Up to16GB unified memory",
    "Up to 2TBstorage",
    "Up to 20 hrsbattery life",
    "Touch Bar and Touch ID"
],
image: "https://i.ibb.co/99WhFWK/compare-macbook-pro-13-spacegray-jy60myikwne6-large.jpg",
manufactured: "2020-09-12T10:00:00Z",
memory: "512 Gig",
newProduct: false,
price: 2100,
related: "mac-pro",
sn: "mac003" 
},
// New stock
{
    
    available: true,
    category: "iphone",
    colors: "Available upon order",
    description:[
        "6.1 inch Super Retina XDR display",
        "Superfast 5G cellular",
        "2x Optical zoom range",
        "Up to 20 hours video playback",
        "Compatible with MagSafe cases, wallets, wireless chargers, and more",
        "Face ID",
    ],
    
    image: "https://i.ibb.co/vVXbrRC/iphone-14.jpg",
    manufactured: "2022-09-24T09:00:00Z",
    memory: "128 Gig",
    newProduct: true,
    price: 1500,
    related: "iphone-14",
    sn: "i039",
    title: "iPhone 14" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "2x Optical zoom range",
            "Up to 20 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Face ID",
        ],
        image: "https://i.ibb.co/vVXbrRC/iphone-14.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "256 Gig",
        newProduct: true,
        price: 1700,
        related: "iphone-14",
        sn: "i040",
        title: "iPhone 14" 
    },

    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "2x Optical zoom range",
            "Up to 20 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Face ID",
        ],
        image: "https://i.ibb.co/vVXbrRC/iphone-14.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "512 Gig",
        newProduct: true,
        price: 2050,
        related: "iphone-14",
        sn: "i041",
        title: "iPhone 14" 
    },

    //iphone 14 plus
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "2x Optical zoom range",
            "Up to 26 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Face ID",
        ],
        image: "https://i.ibb.co/FJ0bNW0/iphone-14-plus.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "128 Gig",
        newProduct: true,
        price: 1700,
        related: "iphone-14-plus",
        sn: "i042",
        title: "iPhone 14 Plus" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "2x Optical zoom range",
            "Up to 26 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Face ID",
        ],
        image: "https://i.ibb.co/FJ0bNW0/iphone-14-plus.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "256 Gig",
        newProduct: true,
        price: 1900,
        related: "iphone-14-plus",
        sn: "i043",
        title: "iPhone 14 Plus" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "2x Optical zoom range",
            "Up to 26 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Face ID",
        ],
        image: "https://i.ibb.co/FJ0bNW0/iphone-14-plus.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "512 Gig",
        newProduct: true,
        price: 2350,
        related: "iphone-14-plus",
        sn: "i044",
        title: "iPhone 14 Plus" 
    },

    // iphone 14 Pro
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 23 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/kGbMGwV/iphone-14-pro.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "128 Gig",
        newProduct: true,
        price: 1800,
        related: "iphone-14-pro",
        sn: "i045",
        title: "iPhone 14 Pro" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 23 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/kGbMGwV/iphone-14-pro.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "256 Gig",
        newProduct: true,
        price: 2000,
        related: "iphone-14-pro",
        sn: "i046",
        title: "iPhone 14 Pro" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 23 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/kGbMGwV/iphone-14-pro.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "512 Gig",
        newProduct: true,
        price: 2350,
        related: "iphone-14-pro",
        sn: "i047",
        title: "iPhone 14 Pro" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 23 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/kGbMGwV/iphone-14-pro.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "1TB",
        newProduct: true,
        price: 2700,
        related: "iphone-14-pro",
        sn: "i048",
        title: "iPhone 14 Pro" 
    },

    // Iphone 14 pro max
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 29 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/bzQP2b4/iphone-14-pro-max.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "128 Gig",
        newProduct: true,
        price: 2000,
        related: "iphone-14-pro-max",
        sn: "i049",
        title: "iPhone 14 Pro Max" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 29 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/bzQP2b4/iphone-14-pro-max.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "256 Gig",
        newProduct: true,
        price: 2200,
        related: "iphone-14-pro-max",
        sn: "i050",
        title: "iPhone 14 Pro Max" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 29 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/bzQP2b4/iphone-14-pro-max.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "512 Gig",
        newProduct: true,
        price: 2550,
        related: "iphone-14-pro-max",
        sn: "i051",
        title: "iPhone 14 Pro Max" 
    },
    {
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.7 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "6x Optical zoom range",
            "Up to 29 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Dynamic Island A new way to interact with iPhone",
        ],
        image: "https://i.ibb.co/bzQP2b4/iphone-14-pro-max.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "1TB",
        newProduct: true,
        price: 2900,
        related: "iphone-14-pro-max",
        sn: "i052",
        title: "iPhone 14 Pro Max" 
    },

    // Watch New Stock
    {
        title:"Apple Watch Series 8",
        price:800,
        description:[
            "Always-On Retina display",
            "50m Water resistant",
            "Temperature sensing",
            "Redesigned Compass app with waypoints and Backtrack",
            "Up to 18 hours, Fast charge",
            "Available cellular connectivity",
            "Blood Oxygen app",
       ],
        memory: "41mm",
        available: true,
        category:"apple-watch",
        image:"https://i.ibb.co/s32jsqR/series-8.jpg",
        newProduct:true,
        sn:"iw010",
        related:"watch-series-8",
        manufactured:"2022-09-18T00:00:00Z",
        colors:"Available upon order"
    },
    {
        title:"Apple Watch Series 8",
        price:860,
        description:[
            "Always-On Retina display",
            "50m Water resistant",
            "Temperature sensing",
            "Redesigned Compass app with waypoints and Backtrack",
            "Up to 18 hours, Fast charge",
            "Available cellular connectivity",
            "Blood Oxygen app",
       ],
        memory: "45mm",
        available: true,
        category:"apple-watch",
        image:"https://i.ibb.co/s32jsqR/series-8.jpg",
        newProduct:true,
        sn:"iw011",
        related:"watch-series-8",
        manufactured:"2022-09-18T00:00:00Z",
        colors:"Available upon order"
    },

    {
        title:"Apple Watch Ultra",
        price:1600,
        description:[
            "Always-On Retina display",
            "100m Water resistant",
            "Temperature sensing",
            "Redesigned Compass app with waypoints and Backtrack",
            "Up to 36 hours, Fast charge",
            "Available cellular connectivity",
            "Blood Oxygen app",
       ],
        memory: "49mm",
        available: true,
        category:"apple-watch",
        image:"https://i.ibb.co/rcfj1WL/ultra.jpg",
        newProduct:true,
        sn:"iw012",
        related:"watch-series-ultra",
        manufactured:"2022-09-18T00:00:00Z",
        colors:"Available upon order"
    },

    // Air pods Pro
    {
        title:"Airpod Pro 2nd Gen",
        price:550,
        description:[
            "Active Noise Cancellation",
            "Adaptive Transparency",
            "Touch control",
            "Personalized Spatial Audio with dynamic head tracking",
            "Sweat and water resistant: AirPods Pro and charging case",
            "H2 chip",
            "6 hrsUp to 6 hours of listening time on one charge",
            "Up to 30 hours of listening time with charging case",
            "Automatic switching"
        ],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/HzWk9KJ/airpods-pro-2nd.png",
        newProduct:true,
        sn:"ia005",
        related:"airpod-pro",
        colors:"Available upon order",
        manufactured:"2022-09-18T00:00:00Z",
    }, 
]


export const featured = [
    {
    
        available: true,
        category: "iphone",
        colors: "Available upon order",
        description:[
            "6.1 inch Super Retina XDR display",
            "Superfast 5G cellular",
            "2x Optical zoom range",
            "Up to 20 hours video playback",
            "Compatible with MagSafe cases, wallets, wireless chargers, and more",
            "Face ID",
        ],
        
        image: "https://i.ibb.co/vVXbrRC/iphone-14.jpg",
        manufactured: "2022-09-24T09:00:00Z",
        memory: "128 Gig",
        newProduct: true,
        price: 1500,
        related: "iphone-14",
        sn: "i039",
        title: "iPhone 14" 
        },
    {
            available: true,
            category: "iphone",
            colors: "Available upon order",
            description:[
                "6.7 inch Super Retina XDR display",
                "Superfast 5G cellular",
                "2x Optical zoom range",
                "Up to 26 hours video playback",
                "Compatible with MagSafe cases, wallets, wireless chargers, and more",
                "Face ID",
            ],
            image: "https://i.ibb.co/FJ0bNW0/iphone-14-plus.jpg",
            manufactured: "2022-09-24T09:00:00Z",
            memory: "128 Gig",
            newProduct: true,
            price: 1700,
            related: "iphone-14-plus",
            sn: "i042",
            title: "iPhone 14 Plus" 
        },
    
    {
            available: true,
            category: "iphone",
            colors: "Available upon order",
            description:[
                "6.1 inch Super Retina XDR display",
                "Superfast 5G cellular",
                "6x Optical zoom range",
                "Up to 23 hours video playback",
                "Compatible with MagSafe cases, wallets, wireless chargers, and more",
                "Dynamic Island A new way to interact with iPhone",
            ],
            image: "https://i.ibb.co/kGbMGwV/iphone-14-pro.jpg",
            manufactured: "2022-09-24T09:00:00Z",
            memory: "128 Gig",
            newProduct: true,
            price: 1800,
            related: "iphone-14-pro",
            sn: "i045",
            title: "iPhone 14 Pro" 
        },
    
    {
            available: true,
            category: "iphone",
            colors: "Available upon order",
            description:[
                "6.7 inch Super Retina XDR display",
                "Superfast 5G cellular",
                "6x Optical zoom range",
                "Up to 29 hours video playback",
                "Compatible with MagSafe cases, wallets, wireless chargers, and more",
                "Dynamic Island A new way to interact with iPhone",
            ],
            image: "https://i.ibb.co/bzQP2b4/iphone-14-pro-max.jpg",
            manufactured: "2022-09-24T09:00:00Z",
            memory: "128 Gig",
            newProduct: true,
            price: 2000,
            related: "iphone-14-pro-max",
            sn: "i049",
            title: "iPhone 14 Pro Max" 
        },
    
    {
            title:"Apple Watch Series 8",
            price:800,
            description:[
                "Always-On Retina display",
                "50m Water resistant",
                "Temperature sensing",
                "Redesigned Compass app with waypoints and Backtrack",
                "Up to 18 hours, Fast charge",
                "Available cellular connectivity",
                "Blood Oxygen app",
           ],
            memory: "41mm",
            available: true,
            category:"apple-watch",
            image:"https://i.ibb.co/s32jsqR/series-8.jpg",
            newProduct:true,
            sn:"iw010",
            related:"watch-series-8",
            manufactured:"2022-09-18T00:00:00Z",
            colors:"Available upon order"
        },
    
    {
            title:"Airpod Pro 2nd Gen",
            price:550,
            description:[
                "Active Noise Cancellation",
                "Adaptive Transparency",
                "Touch control",
                "Personalized Spatial Audio with dynamic head tracking",
                "Sweat and water resistant: AirPods Pro and charging case",
                "H2 chip",
                "6 hrsUp to 6 hours of listening time on one charge",
                "Up to 30 hours of listening time with charging case",
                "Automatic switching"
            ],
            memory: 0,
            available: true,
            category:"accessories",
            image:"https://i.ibb.co/HzWk9KJ/airpods-pro-2nd.png",
            newProduct:true,
            sn:"ia005",
            related:"airpod-pro",
            colors:"Available upon order",
            manufactured:"2022-09-18T00:00:00Z"
        }, 
    {
                        title:"Apple Watch SE",
                        price:500,
                        description:[
                            "Retina display",
                            "Water resistant",
                            "Cycle Tracking",
                            "Redesigned Compass app with waypoints and Backtrack",
                            "Up to 18 hours",
                            "Available cellular connectivity",
                       ],
                        memory: "40mm",
                        available: true,
                        category:"apple-watch",
                        image:"https://i.ibb.co/jznYdwD/se.jpg",
                        newProduct:true,
                        sn:"iw006",
                        related:"watch-SE",
                        manufactured:"2022-09-18T00:00:00Z",
                        colors:"Available upon order"
                    },
]



