export const products = [
    {
        iphone: {
            id:1,
            title:"iphone",
            items: [
                {
                    title:"iPhone 7 Plus",
                    price:600,
                    description:"",
                    memory: 32,
                    stock: 3,
                    category:"iphone-7",
                    image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
                    newProduct:false,
                    sn:"i12"
                },
                {
                    title:"iPhone 7 Plus",
                    price:650,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:1,
                    image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
                    newProduct:false,
                    sn:"i13"
                },
                {
                    title:"iPhone 8",
                    price:600,
                    description:"",
                    memory: 64,
                    stock: 3,
                    category:"iphone-8",
                    image:"https://i.ibb.co/5Gky7XQ/iphone-8.jpg",
                    newProduct:false,
                    sn:"i14"
                },
                {
                    title:"iPhone 8 Plus",
                    price:800,
                    description:"",
                    memory: 64,
                    stock: 3,
                    category:"iphone-8",
                    image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
                    newProduct:false,
                    sn:"i15"
                },
                {
                    title:"iPhone 8 Plus",
                    price:900,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:"iphone-8",
                    image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
                    newProduct:false,
                    sn:"i16"
                },
                {
                    title:"iPhone X",
                    price:850,
                    description:"",
                    memory: 64,
                    stock: 3,
                    category:"iphone-x",
                    image:"https://i.ibb.co/MNWmxd2/iphone-x.jpg",
                    newProduct:false,
                    sn:"i17"
                },
                {
                    title:"iPhone XR",
                    price:900,
                    description:"",
                    memory: 64,
                    stock: 3,
                    category:"iphone-x",
                    image:"https://i.ibb.co/n8j52rM/iphone-xr.jpg",
                    newProduct:false,
                    sn:"i18"
                },
                {
                    title:"iPhone XS MAX",
                    price:1150,
                    description:"",
                    memory: 64,
                    stock: 3,
                    category:"iphone-x",
                    image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
                    newProduct:false,
                    sn:"i19"
                },
                {
                    title:"iPhone XS MAX",
                    price:1250,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:"iphone-x",
                    image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
                    newProduct:false,
                    sn:"i20"
                },
                {
                    title:"iPhone 11",
                    price:1200,
                    description:"",
                    memory: 128,
                    stock: 3,
                    category:"iphone-11",
                    image:"https://i.ibb.co/RCmz9bx/iphone-11.jpg",
                    newProduct:false,
                    sn:"i21"
                },
                {
                    title:"iPhone 11 Pro",
                    price:1400,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:"iphone-11",
                    image:"https://i.ibb.co/W2ddNbJ/iphone-11-Pro.jpg",
                    newProduct:false,
                    sn:"i223"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1750,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:"iphone-11",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i22"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1900,
                    description:"",
                    memory: 512,
                    stock: 3,
                    category:"iphone-11",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i23"
                },
                {
                    title:"iPhone 12",
                    price:1550,
                    description:"",
                    memory: 128,
                    stock: 3,
                    category:"iphone-12",
                    image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
                    newProduct:true,
                    sn:"i24"
                },
                {
                    title:"iPhone 12 Pro",
                    price:1800,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:"iphone-12",
                    image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
                    newProduct:true,
                    sn:"i25"
                },
                {
                    title:"iPhone 12 Pro",
                    price:2000,
                    description:"",
                    memory: 512,
                    stock: 3,
                    category:"iphone-12",
                    image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
                    newProduct:true,
                    sn:"i26"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:2000,
                    description:"",
                    memory: 128,
                    stock: 3,
                    category:"iphone-12",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:true,
                    sn:"i27"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:2200,
                    description:"",
                    memory: 256,
                    stock: 3,
                    category:"iphone-12",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:true,
                    sn:"i28"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:2400,
                    description:"",
                    memory: 512,
                    stock: 3,
                    category:"iphone-12",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:true,
                    sn:"i29"
                }
    
            
            ]
        }
    }
    
]





export const devices = [
        {
                title:"iPhone 7",
                price:500,
                description:[
                    "Display 4.70-inch (750x1334)",
                    "Processor Apple A10 Fusion",
                    "Front Camera 7MP",
                    "Rear Camera 12MP",
                    "RAM 2GB",
                    "Storage 32GB",
                    "Battery Capacity 1960mAh",
                    "OS iOS 10"
                ],
                memory: 32,
                available: false,
                category:"iphone",
                image:"https://i.ibb.co/jRLJ4qY/iphone-7.jpg",
                newProduct:false,
                sn:"i001",
                related:"iphone-7"
        },
                    {
                        title:"iPhone 7 Plus",
                        price:600,
                        description:[
                            "Retina HD display",
                            "5.5-inch (diagonal) widescreen LCD",
                            "Multi-Touch display with IPS technology",
                            "1920-by-1080-pixel resolution at 401 ppi",
                            "1300:1 contrast ratio (typical)",
                            "Wide color display (P3)",
                            "625 cd/m2 max brightness (typical)",
                            "Dual-domain pixels for wide viewing angles"
                        ],
                        memory: 32,
                        available: true,
                        category:"iphone",
                        image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
                        newProduct:false,
                        sn:"i002",
                        related:"iphone-7"
                    },
                    {
                        title:"iPhone 7 Plus",
                        price:650,
                        description:[
                            "Retina HD display",
                            "5.5-inch (diagonal) widescreen LCD",
                            "Multi-Touch display with IPS technology",
                            "1920-by-1080-pixel resolution at 401 ppi",
                            "1300:1 contrast ratio (typical)",
                            "Wide color display (P3)",
                            "625 cd/m2 max brightness (typical)",
                            "Dual-domain pixels for wide viewing angles"
                        ],
                        memory: 256,
                        available: true,
                        category:"iphone",
                        image:"https://i.ibb.co/Rb51gKw/7-plus.jpg",
                        newProduct:false,
                        sn:"i003",
                        related:"iphone-7"
                    },
        {
            title:"iPhone 8",
            price:600,
            description:[
                "4.7 and 5.5-inch LCD display",
                "Faster A11 processor",
                "Glass body",
                "Upgraded camera",
                "Louder speakers",
                "Wireless inductive charging"
            ],
            memory: 64,
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/5Gky7XQ/iphone-8.jpg",
            newProduct:false,
            sn:"i004",
            related:"iphone-8"
        },
                {
                    title:"iPhone 8 Plus",
                    price:800,
                    description:[
                        "Retina HD display",
                        "5.5-inch (diagonal) widescreen LCD Multi-Touch display with IPS technology",
                        "1920-by-1080-pixel resolution at 401 ppi",
                        "1300:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch",
                        "625 nits max brightness (typical)"
                    ],
                    memory: 64,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
                    newProduct:false,
                    sn:"i005",
                    related:"iphone-8"
                },
                {
                    title:"iPhone 8 Plus",
                    price:900,
                    description:[
                        "Retina HD display",
                        "5.5-inch (diagonal) widescreen LCD Multi-Touch display with IPS technology",
                        "1920-by-1080-pixel resolution at 401 ppi",
                        "1300:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch",
                        "625 nits max brightness (typical)"
                    ],
                    memory: 256,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/3cSx8Xg/iphone-8-plus.jpg",
                    newProduct:false,
                    sn:"i006",
                    related:"iphone-8"
                },
        {
            title:"iPhone X",
            price:850,
            description:[
                "5.8 OLED display",
                "Faster A11 Bionic processor",
                "Glass body",
                "Edge-to-edge display",
                "Facial Recognition",
                "No Home button",
                "Wireless inductive charging",
                "Animoji"
            ],
            memory: 64,
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/MNWmxd2/iphone-x.jpg",
            newProduct:false,
            sn:"i007",
            related:"iphone-x"
        },
        
                {
                    title:"iPhone XR",
                    price:900,
                    description:[
                        "6 New Colors",
                        "A12 Bionic Chip",
                        "Face ID and TrueDepth Camera System",
                        "Haptic Touch",
                        "Smart HDR",
                        "Portrait Mode on Single Camera",
                        "Dual SIM",
                        "Longer Battery Life"
                    ],
                    memory: 64,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/n8j52rM/iphone-xr.jpg",
                    newProduct:false,
                    sn:"i008",
                    related:"iphone-x"
                },


                {
                    title:"iPhone XS MAX",
                    price:1150,
                    description:[
                        "Super Retina HD display",
                        "6.5‑inch (diagonal) all‑screen OLED Multi‑Touch display",
                        "HDR display",
                        "2688‑by-1242‑pixel resolution at 458 ppi",
                        "1,000,000:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch"
                    ],
                    memory: 64,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
                    newProduct:false,
                    sn:"i009",
                    related:"iphone-x"
                },
                {
                    title:"iPhone XS MAX",
                    price:1250,
                    description:[
                        "Super Retina HD display",
                        "6.5‑inch (diagonal) all‑screen OLED Multi‑Touch display",
                        "HDR display",
                        "2688‑by-1242‑pixel resolution at 458 ppi",
                        "1,000,000:1 contrast ratio (typical)",
                        "True Tone display",
                        "Wide color display (P3)",
                        "3D Touch"
                    ],
                    memory: 256,
                    available: true,
                    category:"iphone-x",
                    image:"https://i.ibb.co/jG6DFL2/iphone-xmas.jpg",
                    newProduct:false,
                    sn:"i010",
                    related:"iphone-x"
                },

        {
            title:"iPhone 11",
            price:1200,
            description:[        
                "Processor: Apple A13 Bionic (7 nm+)",
                "RAM: 4 GB",
                "Storage: 64 GB, 128 GB, 256 GB",
                "Display: 6.1 inches",
                "Camera: 12 MP (wide) + 12 MP (ultrawide)",
                "Battery: Non-removable Li-Ion 3110 mAh battery + Fast battery charging 18W: 50% in 30 min",
            ],
            memory: 128,
            stock: 3,
            category:"iphone",
            image:"https://i.ibb.co/RCmz9bx/iphone-11.jpg",
            newProduct:false,
            sn:"i011",
            related:"iphone-11"
        },

                {
                    title:"iPhone 11 Pro",
                    price:1400,
                    description:[         
                        "Display. Screen size (inches) 5.80. Touchscreen",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: 256,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/W2ddNbJ/iphone-11-Pro.jpg",
                    newProduct:false,
                    sn:"i012",
                    related:"iphone-11"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1750,
                    description:[
                        "Display. Screen size (inches) 6.50. Touchscreen.",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: 256,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i013",
                    related:"iphone-11"
                },
                {
                    title:"iPhone 11 Pro Max",
                    price:1900,
                    description:[
                        "Display. Screen size (inches) 6.50. Touchscreen.",
                        "Hardware. Processor. hexa-core. Processor make",
                        "Camera. Rear camera. 12-megapixel (f/1.8) + 12-megapixel (f/2.4) + 12-megapixel (f/2.0)",
                        "Software. Operating system. iOS 13",
                        "Connectivity. Wi-Fi. Yes",
                        "Sensors. Face unlock. Yes"
                    ],
                    memory: 512,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/w4cYT0g/iphone-11-Pro-Max.jpg",
                    newProduct:false,
                    sn:"i014",
                    related:"iphone-11"
                },      
        {
            title:"iPhone 12",
            price:1550,
            description:[
                "iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution",
                "Dual camera setup on rear with features like autofocus and more",
                "Front camera is of 12 MP",
                "Runs iOS 14",
                "64GB inbuilt storage",
                "Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams"
            ],
            memory: 128,
            available: true,
            category:"iphone",
            image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
            newProduct:true,
            sn:"i015",
            related:"iphone-12"
        },
        
                {
                    title:"iPhone 12 Pro",
                    price:1800,
                    description:["iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution.",
                        "Dual camera setup on rear with features like autofocus and more.",
                        "Front camera is of 12 MP.",
                        "Runs iOS 14.",
                        "64GB inbuilt storage.",
                        "Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams."
                    ],
                    memory: 256,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
                    newProduct:true,
                    sn:"i016",
                    related:"iphone-12"
                },
                {
                    title:"iPhone 12 Pro",
                    price:2000,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: 512,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/H2LMyvB/compare-iphone12-pro-pacific-blue-brjnr8xyuewi-large.jpg",
                    newProduct:true,
                    sn:"i017",
                    related:"iphone-12"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:2000,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: 128,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:true,
                    sn:"i018",
                    related:"iphone-12"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:2200,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: 256,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:true,
                    sn:"i019",
                    related:"iphone-12"
                },
                {
                    title:"iPhone 12 Pro Max",
                    price:2400,
                    description:[
                        "Pro 12MP camera system: Ultra Wide, Wide, and Telephoto cameras",
                        "Ultra Wide: ƒ/2.4 aperture and 120° field of view",
                        "Wide: ƒ/1.6 aperture",
                        "Telephoto: ƒ/2.0 aperture (iPhone 12 Pro); ƒ/2.2 aperture (iPhone 12 Pro Max)",
                        "2x optical zoom in, 2x optical zoom out; 4x optical zoom range (iPhone 12 Pro)"
                    ],
                    memory: 512,
                    available: true,
                    category:"iphone",
                    image:"https://i.ibb.co/bbPTqQZ/iphone-12-max.jpg",
                    newProduct:true,
                    sn:"i020",
                    related:"iphone-12"
                },
                {
                    title:"Apple Watch Series 5",
                    price:650,
                    description:["GPS/GNSS",
                    "Compass",
                    "Barometric altimeter",
                    "Water resistant",
                    "50 meters",
                    "Electrical heart sensor",
                    "Second-generation optical heart sensor",
                    "International emergency calling",
                    "Emergency SOS",
                    "Accelerometer"],
                    memory: "44mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/1bgWSFj/watch-series-5.jpg",
                    newProduct:false,
                    sn:"iw001",
                    related:"watch-5"
                },
                {
                    title:"Apple Watch Series 6",
                    price:750,
                    description:["Accelerometer", 
                    "gyro", 
                    "heart rate (2nd gen)",
                    "barometer", 
                     "always-on altimeter", 
                     "compass", 
                     "SpO2", 
                     "VO2max"],
                    memory: "42mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/X2BcctH/watch-series-6.jpg",
                    newProduct:false,
                    sn:"iw002",
                    related:"watch-6"
                },
                {
                    title:"Apple Watch Series 6",
                    price:800,
                    description:["Accelerometer", 
                    "gyro", 
                    "heart rate (2nd gen)",
                    "barometer", 
                    "always-on altimeter", 
                    "compass", 
                    "SpO2", 
                    "VO2max"],
                    memory: "44mm",
                    available: true,
                    category:"apple-watch",
                    image:"https://i.ibb.co/X2BcctH/watch-series-6.jpg",
                    newProduct:false,
                    sn:"iw002",
                    related:"watch-6"
                },
                {
                    title:"iPad 7th Gen",
                    price:700,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: 128,
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/g3Pnx9v/ipad-7thgen.jpg",
                    newProduct:false,
                    sn:"ip001",
                    related:"ipad"
                },
                {
                    title:"iPad 8th Gen",
                    price:800,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: 128,
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/g3Pnx9v/ipad-7thgen.jpg",
                    newProduct:false,
                    sn:"ip002",
                    related:"ipad"
                },
                {
                    title:"iPad Air 2020",
                    price:1300,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: 128,
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/029qhVN/ipad-air-1st-gen-silver.jpg",
                    newProduct:false,
                    sn:"ip003",
                    related:"ipad-air"
                },
                {
                    title:"iPad Pro 2020",
                    price:1700,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: 128,
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/9bxfxmt/ipad-pro-11.jpg",
                    newProduct:false,
                    sn:"ip004",
                    related:"ipad-pro"
                },
                {
                    title:"iPad Pro 2020",
                    price:2100,
                    description:["Voice Control",
                    "VoiceOver",
                    "Zoom",
                    "Magnifier",
                    "Siri and Dictation",
                    "Switch Control",
                    "Closed Captions",
                    "AssistiveTouch",
                    "Speak Screen"],
                    memory: 128,
                    available: true,
                    category:"ipad",
                    image:"https://i.ibb.co/9bxfxmt/ipad-pro-11.jpg",
                    newProduct:false,
                    sn:"ip005",
                    related:"ipad-pro"
                },

                {
                    title:"Airpod 1st Gen",
                    price:200,
                    description:[
                        "Zero wires",
                        "Comfortable fit",
                        "Five hour battery life",
                        "24 hour total battery life with Charging Case",
                        "3 hours charge from case in 15 minutes",
                        "One tap setup for Apple devices",
                        "Instant connection to ‌iPhone‌, ‌iPad‌, Mac, or Apple Watch",
                        "Easy switching between iOS and Mac devices"
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/wK3fffV/MRXJ2.png",
                    newProduct:false,
                    sn:"ia001",
                    related:"airpod-pro"
                },
                {
                    title:"Airpod 2nd Gen",
                    price:200,
                    description:[
                        "Zero wires",
                        "Comfortable fit",
                        "Five hour battery life",
                        "24 hour total battery life with Charging Case",
                        "3 hours charge from case in 15 minutes",
                        "One tap setup for Apple devices",
                        "Instant connection to ‌iPhone‌, ‌iPad‌, Mac, or Apple Watch",
                        "Easy switching between iOS and Mac devices"
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/wK3fffV/MRXJ2.png",
                    newProduct:false,
                    sn:"ia002",
                    related:"airpod-pro"
                },
                {
                    title:"Airpod Pro",
                    price:380,
                    description:["Active Noise Cancellation",
                    "Adaptive EQ",
                    "Dual beamforming microphones",
                    "Force sensor",
                    "Sweat and water resistant (IPX4)",
                    "Vent system for pressure equalization",
                    "Spatial audio with dynamic head tracking",
                    "Dual optical sensors",
                    "Speech-detecting accelerometer"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/XFw90tX/airpods-pro-qwgxmyvspfey-large.jpg",
                    newProduct:false,
                    sn:"ia003",
                    related:"airpod-pro"
                },
                {
                    title:"EarPods Lightning",
                    price:45,
                    description:["The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. "],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/jL9F0xB/MMTN2.jpg",
                    newProduct:false,
                    sn:"ias002",
                    related:"earpods"
                },
                {
                    title:"EarPods Jack",
                    price:30,
                    description:["The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. "],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/jL9F0xB/MMTN2.jpg",
                    newProduct:false,
                    sn:"ias003",
                    related:"earpods"
                },
                {
                    title:"Lightning",
                    price:30,
                    description:["This USB 2.0 cable connects your iPhone, iPad, or iPod with Lightning connector to your computer’s USB port for syncing and charging. Or you can connect to the Apple USB Power Adapter for convenient charging from a wall outlet."],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/v1t5gm4/MD818.jpg",
                    newProduct:false,
                    sn:"ias004",
                    related:"cable"
                },
                {
                    title:"9D(6-8 Plus)",
                    price:15,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/HY386fr/129907-5085-ipxr19-sty-clr-2.jpg",
                    newProduct:false,
                    sn:"ias005",
                    related:"tempered"
                },
                {
                    title:"9D(X- 11 Pro Max)",
                    price:20,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/HY386fr/129907-5085-ipxr19-sty-clr-2.jpg",
                    newProduct:false,
                    sn:"ias006",
                    related:"tempered"
                },
                {
                    title:"9D(iphone 12- 12 Pro Max)",
                    price:40,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/HY386fr/129907-5085-ipxr19-sty-clr-2.jpg",
                    newProduct:false,
                    sn:"ias007",
                    related:"tempered"
                },
                {
                    title:"Privacy",
                    price:40,
                    description:["100% Brand New and high quality!",
                    "Ultra Slim Thickness",
                    "Bubble Free",
                    "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
                    ],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/HY386fr/129907-5085-ipxr19-sty-clr-2.jpg",
                    newProduct:false,
                    sn:"ias008",
                    related:"tempered"
                },
                {
                    title:"Silicon Case",
                    price:20,
                    description:["100% Brand New and high quality!",
                    "Extreme Protection", "iphone 6 - 8 Plus"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/n05hF6L/silicone-case.png",
                    newProduct:false,
                    sn:"ias009",
                    related:"silicon"
                },
                {
                    title:"Silicon Case",
                    price:40,
                    description:["100% Brand New and high quality!",
                    "Extreme Protection", "iphone X - 12 Pro Max"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/n05hF6L/silicone-case.png",
                    newProduct:false,
                    sn:"ias010",
                    related:"silicon"
                },
                {
                    title:"Clear Case",
                    price:15,
                    description:["100% Brand New and high quality!",
                    "Beautiful Design", "iphone 6 - 8 Plus"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/HVp4xbw/s-l1600.jpg",
                    newProduct:false,
                    sn:"ias011",
                    related:"clear"
                },

                {
                    title:"Clear Case",
                    price:30,
                    description:["100% Brand New and high quality!",
                    "Beautiful Design", "iphone X - 12 Pro Max"],
                    memory: 0,
                    available: true,
                    category:"accessories",
                    image:"https://i.ibb.co/HVp4xbw/s-l1600.jpg",
                    newProduct:false,
                    sn:"ias012",
                    related:"clear"
                },

]


export const featured = [
    {
        title:"iPhone 12",
        price:1550,
        description:["iPhone 12 has 6.10-inch display and 1170x2532 pixels resolution.",
        "Dual camera setup on rear with features like autofocus and more.",
        "Front camera is of 12 MP.",
        "Runs iOS 14.",
        "64GB inbuilt storage.",
        "Dimensions of the phone are 146.70 mm x 71.50 mm x 7.40 mm; weight is 164 grams."],
        memory: 128,
        available: true,
        category:"iphone",
        image:"https://i.ibb.co/LC24X54/iphone-12.jpg",
        newProduct:true,
        sn:"i015",
        related:"iphone-12"
    },
    
    {
        title:"iPhone 11",
        price:1200,
        description:[
            "Processor: Apple A13 Bionic (7 nm+)",
            "RAM: 4 GB",
            "Storage: 64 GB, 128 GB, 256 GB",
            "Display: 6.1 inches",
            "Camera: 12 MP (wide) + 12 MP (ultrawide)",
            "Battery: Non-removable Li-Ion 3110 mAh battery + Fast battery charging 18W: 50% in 30 min",
        ],
        memory: 128,
        available: true,
        category:"iphone",
        image:"https://i.ibb.co/RCmz9bx/iphone-11.jpg",
        newProduct:false,
        sn:"i011",
        related:"iphone-11"
    },
    {
        title:"Apple Watch Series 5",
        price:650,
        description:["GPS/GNSS",
        "Compass",
        "Barometric altimeter",
        "Water resistant",
        "50 meters",
        "Electrical heart sensor",
        "Second-generation optical heart sensor",
        "International emergency calling",
        "Emergency SOS",
        "Accelerometer"],
        memory: "44mm",
        available: true,
        category:"apple-watch",
        image:"https://i.ibb.co/1bgWSFj/watch-series-5.jpg",
        newProduct:false,
        sn:"iw001",
        related:"watch-5"
    },
    {
        title:"Apple Watch Series 6",
        price:750,
        description:["Accelerometer", 
        "gyro", 
        "heart rate (2nd gen)",
        "barometer", 
         "always-on altimeter", 
         "compass", 
         "SpO2", 
         "VO2max"],
        memory: "42mm",
        available: true,
        category:"apple-watch",
        image:"https://i.ibb.co/X2BcctH/watch-series-6.jpg",
        newProduct:false,
        sn:"iw002",
        related:"watch-6"
    },
    {
        title:"iPad 7th Gen",
        price:700,
        description:["Voice Control",
        "VoiceOver",
        "Zoom",
        "Magnifier",
        "Siri and Dictation",
        "Switch Control",
        "Closed Captions",
        "AssistiveTouch",
        "Speak Screen"],
        memory: 128,
        available: true,
        category:"ipad",
        image:"https://i.ibb.co/g3Pnx9v/ipad-7thgen.jpg",
        newProduct:false,
        sn:"ip001",
        related:"ipad"
    },
    {
        title:"iPad Air 2020",
        price:1300,
        description:["Voice Control",
        "VoiceOver",
        "Zoom",
        "Magnifier",
        "Siri and Dictation",
        "Switch Control",
        "Closed Captions",
        "AssistiveTouch",
        "Speak Screen"],
        memory: 128,
        available: true,
        category:"ipad",
        image:"https://i.ibb.co/029qhVN/ipad-air-1st-gen-silver.jpg",
        newProduct:false,
        sn:"ip003",
        related:"ipad-air"
    },

    {
        title:"iPad Pro 2020",
        price:1700,
        description:["Voice Control",
        "VoiceOver",
        "Zoom",
        "Magnifier",
        "Siri and Dictation",
        "Switch Control",
        "Closed Captions",
        "AssistiveTouch",
        "Speak Screen"],
        memory: 128,
        available: true,
        category:"ipad",
        image:"https://i.ibb.co/9bxfxmt/ipad-pro-11.jpg",
        newProduct:false,
        sn:"ip004",
        related:"ipad-pro"
    },

    {
        title:"Airpod Pro",
        price:380,
        description:["Active Noise Cancellation",
        "Adaptive EQ",
        "Dual beamforming microphones",
        "Force sensor",
        "Sweat and water resistant (IPX4)",
        "Vent system for pressure equalization",
        "Spatial audio with dynamic head tracking",
        "Dual optical sensors",
        "Speech-detecting accelerometer"],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/XFw90tX/airpods-pro-qwgxmyvspfey-large.jpg",
        newProduct:false,
        sn:"ia003",
        related:"airpod-pro"
    },
    {
        title:"EarPods Lightning",
        price:45,
        description:["The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. "],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/jL9F0xB/MMTN2.jpg",
        newProduct:false,
        sn:"ias002",
        related:"earpods"
    },
    {
        title:"Lightning",
        price:30,
        description:["This USB 2.0 cable connects your iPhone, iPad, or iPod with Lightning connector to your computer’s USB port for syncing and charging. Or you can connect to the Apple USB Power Adapter for convenient charging from a wall outlet."],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/v1t5gm4/MD818.jpg",
        newProduct:false,
        sn:"ias004",
        related:"cable"
    },
    {
        title:"Privacy",
        price:40,
        description:["100% Brand New and high quality!",
        "Ultra Slim Thickness",
        "Bubble Free",
        "9H Strong Hardness Anti-Scratch, Real tempered glass protector."
        ],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/HY386fr/129907-5085-ipxr19-sty-clr-2.jpg",
        newProduct:false,
        sn:"ias008",
        related:"tempered"
    },
    {
        title:"Silicon Case",
        price:20,
        description:["100% Brand New and high quality!",
        "Extreme Protection", "iphone 6 - 8 Plus"],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/n05hF6L/silicone-case.png",
        newProduct:false,
        sn:"ias009",
        related:"silicon"
    },
    {
        title:"Clear Case",
        price:15,
        description:["100% Brand New and high quality!",
        "Beautiful Design", "iphone 6 - 8 Plus"],
        memory: 0,
        available: true,
        category:"accessories",
        image:"https://i.ibb.co/HVp4xbw/s-l1600.jpg",
        newProduct:false,
        sn:"ias011",
        related:"clear"
    },
]



